module.exports = {
  AlbumService: require("./album.service"),
  ArtistService: require("./artist.service"),
  CrateService: require("./crate.service"),
  DateService: require("./date.service"),
  DocumentService: require("./document.service"),
  PasswordService: require("./password.service"),
  PlaylistEventService: require("./playlistevent.service"),
  PubSubService: require("./pubsub"),
  SearchService: require("./search.service"),
  SpotService: require("./spot.service"),
  TagEditService: require("./tagedit.service"),
  TrackService: require("./track.service"),
  TrafficLogService: require("./trafficLog.service"),
};
