import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faGripLines,
  faCircleCheck,
  faCircleExclamation,
  faStar,
  faBan,
  faPenToSquare,
  faSquareCheck,
  faXmark,
  faCircle,
  faPlay,
  faRotateRight,
  faPlus,
  faPen,
  faRightToBracket,
  faCirclePause,
  faArrowLeft,
  faCheck,
  faSquareCaretLeft,
  faCirclePlus,
  faCompactDisc,
  faClock,
  faExclamation,
} from "@fortawesome/free-solid-svg-icons";
import { faPenToSquare as farFaPenToSquare } from "@fortawesome/free-regular-svg-icons";

library.add(
  faGripLines,
  faCircleCheck,
  faSquareCheck,
  faCircleExclamation,
  faStar,
  faBan,
  faPenToSquare,
  faXmark,
  faCircle,
  faPlay,
  faRotateRight,
  faPlus,
  faPen,
  faRightToBracket,
  faCirclePause,
  faArrowLeft,
  faCheck,
  faSquareCaretLeft,
  faCirclePlus,
  faCompactDisc,
  farFaPenToSquare,
  faClock,
  faExclamation
);
