module.exports = {
  CURRENT_TAGS: [
    "local_current",
    "local_classic",
    "heavy_rotation",
    "light_rotation",
    "clean",
    "Disc 1",
    "Disc 2",
    "Disc 3",
    "Disc 4",
    "Disc 5",
    "Disc 6",
    "Disc 7",
    "Disc 8",
    "Disc 9",
    "Disc 10",
  ],
  SPOT__VALID_SLOTS: [0, 12, 13, 24, 25, 30, 36, 37, 48, 49, 54, 55],
  ROLES: [
    "reviewer",
    "dj",
    "music_director",
    "volunteer_coordinator",
    "traffic_log_admin",
  ],
};
