service: nextup
runtime: nodejs10
env: standard
includes:
  - env_variables.yaml
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
instance_class: B1
basic_scaling:
  max_instances: 2
  idle_timeout: 5m