openapi: 3.0.0
info:
  version: 1.0.0
  title: NextUp API
  description: An API for working with the CHIRP Radio music library
servers:
  - url: http://nextup.chirpradio.org/api
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Most endpoints require an `Authorization: Bearer <token>` header, where `token` is the value retrieved from authorizing against the /token endpoint."
paths:
  /token:
    post:
      summary: Get an authorization token
      description: Authorize with email and password to retrieve a JSON Web Token (JWT) you can use to authorize against other API endpoints.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password: 
                  type: string
              required:
                - email
                - password
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password: 
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:   
                  token:
                    type: string
  /album/{album_id}:
    get:
      security:
        - Bearer: []
      summary: Get an album
      description: Returns an album, including the artist, tracks, reviews, and comments            
      parameters:
        - name: album_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
        '404':
          description: Not found