name: Lint

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        directory: [app, client]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.directory }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.directory }}

      - name: Run lint
        run: npm run lint
        working-directory: ${{ matrix.directory }}